# -*- coding: utf-8 -*-

MIN_LIGHT_LEVEL = 0
MAX_LIGHT_LEVEL = 210

# Those are from the app .apk

SPP_COMMAND_CHECK = 4
SPP_CHANGE_MODE   = 5
SPP_GET_PLAY_NAME = 6
SPP_GET_MUSIC_LIST = 7
SPP_SET_VOL        = 8
SPP_GET_VOL        = 9
# SPP_SET_PLAY_STATUS(10),
# SPP_GET_PLAY_STATUS(11),
# SPP_SET_EQ_MODE(12),
# SPP_GET_EQ_MODE(13),
# SPP_SET_PLAY_MODE(14),
# SPP_GET_PLAY_MODE(15),
SPP_GET_VOLTAGE = 16
# SPP_SET_PLAY_MUSICID(17),
#         SPP_SET_LAST_NEXT(18),
#         SPP_GET_STDB_MODE(19),
#         SPP_SEND_LIST_OVER(20),
#         SPP_SEND_TF_STATUS(21),
#         SPP_GET_FM_LIST(22),
#         SPP_SET_FM_PLAY_ID(23),
SPP_SET_SYSTEM_TIME = 24
SPP_GET_ALARM_TIME  = 25 # Doesn't work with aurabulb
#         SPP_SET_ALARM_TIME(26),
#         SPP_SET_PLAY_BACK_FORWARD_START(27),
#         SPP_SET_PLAY_BACK_FORWARD_STOP(28),
SPP_GET_PRODUCE_NAME = 29
SPP_GET_SOFTWARE_VERSION = 30
#         SPP_GET_PRODUCER_SERIAL_ID(31),
#         SPP_GET_RECORD_COUNT(32),
#         SPP_GET_REC_CONTENT_BY_ID(33),
#         SPP_SYNCH_SYSTEM_TIME(34),
#         SPP_SET_USERINFO(35),
#         SPP_SYNCH_USERINFO(36),
#         SPP_SHOW_BT_MUSICINFO(37),
#         SPP_SHOW_BT_MUSICNAME(38),
#         SPP_GET_FM_CURRENT_FREQ(39),
#         SPP_SET_FM_CURRENT_FREQ(40),
#         SPP_GET_FM_MAX_MIN_FREQ(41),
#         SPP_SET_FM_AUTOMATIC_SEARCH(42),
#         SPP_GET_FM_COUNT_OR_FREQ(43),
#         SPP_SET_SLEEP_TIME(64),
#         SPP_SET_SLEEP_SCENE(65),
SPP_GET_ALARM_TIME_SCENE = 66
SPP_SET_ALARM_TIME_SCENE = 67
#         SPP_SET_BOX_MODE(69),
#         SPP_LIEGHT_GET_LIGHT_MODE(70),
#         SPP_SET_BOX_RGB(71),
SPP_LIGHT_GET_COLOR = 72
#         SPP_SET_BOX_COLOR(68),
#         SPP_SET_MUL_BOX_COLOR(73),
#         SPP_SET_TEM(76),
#         SPP_SET_ANDROID_ANCS(80),
SPP_LIGHT_TURN_ON_OFF   = 48
SPP_LIGHT_CURRENT_LEVEL = 49
SPP_LIGHT_ADJUST_LEVEL  = 50
#         SPP_GET_ALARM_TIME_EXT(51),
#         SPP_SET_ALARM_TIME_EXT(52),
SPP_COLOR_ADJUST = 53
SPP_LIGHT_SET_MODE = 56

MODE_NORMAL = 1
MODE_FLASHING = 2
MODE_PULSE = 3
MODE_CANDLE = 4
MODE_RAINBOW = 5
MODE_CYCLE = 7 # Discovered myself

SCENE_YELLOW_LIGHT_NO_SOUND = 0
SCENE_YELLOW_BIRDS_AND_RAIN = 1
SCENE_BLUE_THUNDER_AND_RAIN = 2
SCENE_BLUE_WHITE_WAVES      = 3
